config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
variables:
  is_workspace: false
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_allowed_signers:
    src: ssh/allowed_signers
    dst: ~/.ssh/allowed_signers
  f_ssh-find-agent.sh:
    src: ssh-find-agent.sh
    dst: ~/ssh-find-agent.sh
    chmod: '755'
  f_upgrade-ddr:
    src: local/bin/upgrade-ddr
    dst: ~/.local/bin/upgrade-ddr
    chmod: '755'
  f_upgrade-ddtool:
    src: local/bin/upgrade-ddtool
    dst: ~/.local/bin/upgrade-ddtool
    chmod: '755'
  d_grc:
    src: grc
    dst: ~/.grc
  f_gotest.conf:
    src: grc/gotest.conf
    dst: ~/.grc/gotest.conf
  f_grc.conf:
    src: grc/grc.conf
    dst: ~/.grc/grc.conf
  f_aliases:
    src: config/graphite/aliases
    dst: ~/.config/graphite/aliases
profiles:
  common:
    dotfiles:
    - f_ssh-find-agent.sh
    - f_bashrc
    - f_gitconfig
    - f_allowed_signers
  workspace:
    include:
    - common
    variables:
      is_workspace: true
    dotfiles:
    - f_upgrade-ddr
    - f_upgrade-ddtool
    - d_grc
    - f_gotest.conf
    - f_grc.conf
    - f_aliases
  ip-10-126-87-151:
    dotfiles:
    - f_ssh-find-agent.sh
