config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
variables:
  is_workspace: false
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_allowed_signers:
    src: ssh/allowed_signers
    dst: ~/.ssh/allowed_signers
  f_ssh-find-agent.sh:
    src: ssh-find-agent.sh
    dst: ~/ssh-find-agent.sh
    chmod: '755'
profiles:
  common:
    dotfiles:
    - f_ssh-find-agent.sh
    - f_bashrc
    - f_gitconfig
    - f_allowed_signers
  workspace:
    include:
    - common
    variables:
      is_workspace: true
  ip-10-126-87-151:
    dotfiles:
    - f_ssh-find-agent.sh
